import Image from "next/image";

const PrivacyPolicy = () => {
  return (
    <div className="h-full w-full bg-white text-gray-950">
      <div className="container p-8">
        <div className="flex flex-col">
          <header className="flex items-center justify-center gap-4 p-0 text-3xl md:p-12 md:text-2xl">
            <Image
              className="h-16 w-16"
              src="/logo-128.png"
              alt="Omnibrowse logo"
              width={128}
              height={128}
            />
            <h4 className="flex-grow text-3xl md:flex-grow-0">Omnibrowse</h4>
          </header>

          <section className="flex w-full flex-col gap-2">
            <h1 className="mb-10 text-5xl font-bold">Privacy Policy</h1>
            <div className="mb-5 flex flex-col gap-2">
              <p>Update date: April 15, 2024 </p>
              <p>Effective Date: April 15, 2024</p>
            </div>

            <p>
              At Omnibrowse we are committed to protecting your privacy. This
              privacy policy describes our policies and procedures on the
              collection, use and disclosure of your information when you use
              the service and tells you about your privacy rights and how the
              law protects you. We use your personal data to provide and improve
              the service. By using the service, You agree to the collection and
              use of information in accordance with this Privacy Policy.
            </p>

            <h2 className="mt-5 text-3xl font-semibold">
              Interpretation and Definitions
            </h2>

            <h3 className="mb-5 mt-5 text-2xl font-semibold">Interpretation</h3>
            <p>
              The words of which the initial letter is capitalized have meanings
              defined under the following conditions. The following definitions
              shall have the same meaning regardless of whether they appear in
              singular or in plural.
            </p>

            <h3 className="mb-5 mt-5 text-2xl font-semibold">Definitions</h3>
            <p>For the purposes of this Privacy Policy:</p>
            <ul className="list-disc space-y-2 pl-10">
              <li>
                <b>Account</b> means a unique account created for You to access
                our Service or parts of our Service.
              </li>
              <li>
                <b>Application</b> means the software program provided by the
                Company downloaded by You on any electronic device, named
                Omnibrowse extension.
              </li>
              <li>
                <b>Company</b> (referred to as either “the Company”, “We”, “Us”
                or “Our” in this Agreement) refers to Vidline Inc.
              </li>
              <li>
                <b>Device</b> means any device that can access the Service such
                as a computer, a cell phone or a digital tablet.
              </li>
              <li>
                <b>Personal Data</b> is any information that relates to an
                identified or identifiable individual.
              </li>
              <li>
                <b>Service</b> refers to the Application
              </li>
              <li>
                <b>Service Provider</b> means any natural or legal person who
                processes the data on behalf of the Company. It refers to
                third-party companies or individuals employed by the Company to
                facilitate the Service, to provide the Service on behalf of the
                Company, to perform services related to the Service or to assist
                the Company in analyzing how the Service is used.
              </li>
              <li>
                <b>Usage Data</b> refers to data collected automatically, either
                generated by the use of the Service or from the Service
                infrastructure itself (for example, the duration of a page
                visit).
              </li>
              <li>
                <b>You</b> mean the individual accessing or using the Service,
                or the company, or other legal entity on behalf of which such
                individual is accessing or using the Service, as applicable.
              </li>
            </ul>

            <h2 className="mt-10 text-3xl font-semibold">
              Collecting and Using Your Personal Data
            </h2>
            <h3 className="mb-5 mt-5 text-2xl font-semibold">
              Types of Data Collected
            </h3>
            <h4 className="text-1xl mb-1 font-bold">Personal Data</h4>
            <p>
              While using Our Service, We may ask you to provide Us with certain
              personally identifiable information that can be used to contact or
              identify you. Personally identifiable information may include, but
              is not limited to: Your email, your name, your phone number if you
              choose to login with your phone number etc.
            </p>
            <h4 className="text-1xl mb-1 font-bold">Usage Data</h4>
            <p>Usage Data is collected automatically when using the Service.</p>
            <p>
              Usage Data may include information such as Your browser type,
              browser version, the pages of our Service that You visit, the time
              and date of Your visit, the time spent on those pages, unique
              device identifiers and other diagnostic data.
            </p>
            <p>
              When You access the Service through all kinds of OS, We may
              collect certain information including, but not limited to, Your
              operating system, Your app version, and other diagnostic data.
            </p>

            <h3 className="mb-5 mt-5 text-2xl font-semibold">
              Use of Your Personal Data
            </h3>
            <p>The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc space-y-2 pl-10">
              <li>
                <b>To provide and maintain our Service</b>, including to monitor
                the usage of our Service.
              </li>
              <li>
                <b>To manage Your Account:</b> to manage Your registration as a
                user of the Service. The Personal Data You provide can give You
                access to different functionalities of the Service that are
                available to You as a registered user.
              </li>
              <li>
                <b>For the performance of a contract:</b> the development,
                compliance and undertaking of the purchase contract for the
                products, items or services You have purchased or of any other
                contract with Us through the Service.
              </li>
              <li>
                <b>To contact You:</b> To contact You by email or other
                equivalent forms of electronic communication, such as a mobile
                application push notifications regarding updates or informative
                communications related to the functionalities, products or
                contracted services, including the security updates, when
                necessary or reasonable for their implementation.
              </li>
              <li>
                <b>To manage Your requests:</b> To attend and manage Your
                requests to Us.
              </li>
              <li>
                <b>For other purposes:</b> We may use Your information for other
                purposes, such as data analysis, identifying usage trends,
                determining the effectiveness of our promotional campaigns and
                to evaluate and improve our Service, products, services,
                marketing and your experience.
              </li>
            </ul>

            <p>
              We may share Your personal information in the following
              situations:
            </p>
            <ul className="list-disc space-y-2 pl-10">
              <li>
                <b>With Service Providers:</b> We may share Your personal
                information with Service Providers to monitor and analyze the
                use of our Service, to contact You.
              </li>
              <li>
                <b>With other users:</b> when You share personal information or
                otherwise interact in the public areas with other users, such
                information may be viewed by all users and may be publicly
                distributed outside.
              </li>
              <li>
                <b>With Your consent:</b> We may disclose Your personal
                information for any other purpose with Your consent.
              </li>
              <li>
                <b>Third-Party Services:</b> You can choose to permit or
                restrict Third-Party Services. Third-Party Services may
                integrate with our services and you can enable or disable the
                integrations. Once enabled, the Third-Party Service may share
                some information with us to facilitate the integration. You
                should check the privacy settings and notices in these
                Third-Party Services to understand the data collection, sharing
                and use.{" "}
              </li>
            </ul>

            <h3 className="mb-5 mt-5 text-2xl font-semibold">
              Retention of Your Personal Data
            </h3>
            <p>
              The Company will retain Your Personal Data only for as long as is
              necessary for the purposes set out in this Privacy Policy. We will
              retain and use Your Personal Data to the extent necessary to
              comply with our legal obligations (for example, if we are required
              to retain your data to comply with applicable laws), resolve
              disputes, and enforce our legal agreements and policies.
            </p>
            <p>
              The Company will also retain Usage Data for internal analysis
              purposes. Usage Data is generally retained for a shorter period of
              time, except when this data is used to strengthen the security or
              to improve the functionality of Our Service, or We are legally
              obligated to retain this data for longer time periods.
            </p>

            <h3 className="mb-5 mt-5 text-2xl font-semibold">
              Transfer of Your Personal Data
            </h3>
            <p>
              Your information, including Personal Data, is processed at the
              Company operating offices and in any other places where the
              parties involved in the processing are located. It means that this
              information may be transferred to — and maintained on — computers
              located outside of Your state, province, country or other
              governmental jurisdiction where the data protection laws may
              differ from those from Your jurisdiction.
            </p>
            <p>
              Your consent to this Privacy Policy followed by Your submission of
              such information represents Your agreement to that transfer.
            </p>
            <p>
              The Company will take all steps reasonably necessary to ensure
              that Your data is treated securely and in accordance with this
              Privacy Policy and no transfer of Your Personal Data will take
              place to an organization or a country unless there are adequate
              controls in place including the security of Your data and other
              personal information.
            </p>

            <h3 className="mb-5 mt-5 text-2xl font-semibold">
              Delete Your Personal Data
            </h3>
            <p>
              You have the right to delete or request that We assist in deleting
              the Personal Data that We have collected about You.
            </p>
            <p>
              Our Service may give You the ability to delete certain information
              about You from within the Service.
            </p>
            <p>
              You may update, amend, or delete Your information at any time by
              signing in to Your Account, if you have one, and visiting the
              account settings section that allows you to manage Your personal
              information. You may also contact Us to request access to,
              correct, or delete any personal information that You have provided
              to Us.
            </p>
            <p>
              Please note, however, that We may need to retain certain
              information when we have a legal obligation or lawful basis to do
              so.
            </p>

            <p>
              <strong>
                In addition to the aforementioned policy, the following
                information pertains to data collection, handling, storage, and
                sharing by the Chrome/Edge extension and omnibrowse.io web
                service.
              </strong>
            </p>
            <b> Data collection</b>
            <ol className="list-item">
              <li>
                If you choose to save your chats on omnibrowse.io via, your
                chats will be saved on omnibrowse.io servers in Amazon US data
                center.{" "}
              </li>
              <li>
                Your registration data will also be saved on omnibrowse.io
                servers in Amazon US data center.
              </li>
              <li>
                Your browser version may be saved and used to diagnose problems
                you experienced.{" "}
              </li>
              <li>
                If you choose to upload and save files, such as HTML and PDF
                files on omnibrowse.io website, those data will be saved on
                omnibrowse.io servers on Amazon US.{" "}
              </li>
              <li>
                We may use tools like Google analytics to collect usage data.{" "}
              </li>
            </ol>

            <b>Data handling</b>
            <ol>
              <li>Data is transferred to servers through HTTPS.</li>
              <li>
                The company has strict restrictions on your data. Basically, no
                one will be able to access your data unless you request us to
                diagnose data related issues for you.
              </li>
              <li>
                We may get stats information of your data, for example, how many
                new chats the service has today etc.
              </li>
              <li>
                We may use third party services like Google Analytics to collect
                some usage data.{" "}
              </li>
              <li>We will not sell your data to any third party. </li>
              <li>
                You can choose to delete your account and remove all data stored
                in our servers.
              </li>
            </ol>

            <b>Data Storage</b>
            <ol>
              <li>The data is stored in Amazon servers based in the US.</li>
              <li>We use a backup system in Amazon to back up the data.</li>
              <li>
                We utilize security services, such as firewalls, to safeguard
                your data.
              </li>
            </ol>

            <b>Data sharing:</b>
            <ol>
              <li>
                We may use some third party services, such as Google analytics
                to collect some usage data, so some usage data is shared to
                those services.{" "}
              </li>
              <li>
                You can choose to share your chats with AI to other users.{" "}
              </li>
              <li>
                If you choose to Chat with AIs through our tools or services,
                you agree to share those data with AIs and the organization
                behind those AIs.
              </li>
              <li>
                Your chat data is not shared with any other third parties,
                except when required by law enforcement.
              </li>
            </ol>

            <h3 className="mb-5 mt-5 text-2xl font-semibold">
              Disclosure of Your Personal Data
            </h3>
            <h4 className="text-1xl mb-1 font-bold">Business Transactions</h4>
            <p>
              If the Company is involved in a merger, acquisition or asset sale,
              Your Personal Data may be transferred. We will provide notice
              before Your Personal Data is transferred and becomes subject to a
              different Privacy Policy.
            </p>

            <h4 className="text-1xl mb-1 font-bold">Law enforcement</h4>
            <p>
              Under certain circumstances, the Company may be required to
              disclose Your Personal Data if required to do so by law or in
              response to valid requests by public authorities (e.g. a court or
              a government agency).
            </p>

            <h4 className="text-1xl mb-1 font-bold">
              Other legal requirements
            </h4>
            <p>
              The Company may disclose Your Personal Data in the good faith
              belief that such action is necessary to:
            </p>
            <ul className="list-disc space-y-2 pl-10">
              <li>Comply with a legal obligation</li>
              <li>Protect and defend the rights or property of the Company</li>
              <li>
                Prevent or investigate possible wrongdoing in connection with
                the Service
              </li>
              <li>
                Protect the personal safety of Users of the Service or the
                public
              </li>
              <li>Protect against legal liability</li>
            </ul>

            <h4 className="text-1xl mb-1 font-bold">GDPR compliance</h4>
            <p>
              We updated our Privacy Policy to comply with requirements of
              General Data Protection Regulation (GDPR) which is the European
              Union data protection law that goes into effect May 25, 2018.
            </p>

            <h3 className="mb-5 mt-5 text-2xl font-semibold">
              Security of Your Personal Data
            </h3>
            <p>
              The security of Your Personal Data is important to Us, but
              remember that no method of transmission over the Internet, or
              method of electronic storage is 100% secure. While We strive to
              use commercially acceptable means to protect Your Personal Data,
              We cannot guarantee its absolute security.
            </p>

            <h2 className="mt-10 text-3xl font-semibold">Children Privacy</h2>
            <p>
              Our Service does not address anyone under the age of 13. We do not
              knowingly collect personally identifiable information from anyone
              under the age of 13. If You are a parent or guardian and You are
              aware that Your child has provided Us with Personal Data, please
              contact Us. If We become aware that We have collected Personal
              Data from anyone under the age of 13 without verification of
              parental consent, We take steps to remove that information from
              Our servers.
            </p>
            <p>
              If We need to rely on consent as a legal basis for processing Your
              information and Your country requires consent from a parent, We
              may require Your parents consent before We collect and use that
              information.
            </p>

            <h2 className="mt-10 text-3xl font-semibold">
              Links to Other Websites
            </h2>
            <p>
              Our Service may contain links to other websites that are not
              operated by Us. If You click on a third party link, You will be
              directed to that third party site. We strongly advise You to
              review the Privacy Policy of every site You visit.
            </p>
            <p>
              We have no control over and assume no responsibility for the
              content, privacy policies or practices of any third party sites or
              services.
            </p>

            <h2 className="mt-10 text-3xl font-semibold">
              Changes to this Privacy Policy
            </h2>
            <p>
              We may update Our Privacy Policy from time to time. We will notify
              You of any changes by posting the new Privacy Policy on this page.
            </p>
            <p>
              You are advised to review this Privacy Policy periodically for any
              changes. Changes to this Privacy Policy are effective when they
              are posted on this page.
            </p>
          </section>

          <footer className="flex flex-col py-5 ">
            <h2 className="mt-10 text-2xl font-semibold">Contact Us</h2>
            <p>
              If you have any questions about this Privacy Policy, You can
              contact us:
            </p>
            <p>
              By email:{" "}
              <a href="mailto:help@omnibrowse.io" className="text-blue-600">
                help@omnibrowse.io
              </a>
            </p>
          </footer>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
